lecturer('Nattapong', 'DM', 1).
lecturer('Visit', 'SEP', 2).
lecturer('Udom', 'LA', 2).
lecturer('Suphamit', 'DB', 2).
lecturer('Pipat', 'Network', 2).
lecturer('Nattapong', 'ADA', 2).
lecturer('Visit', 'KRR', 3).
lecturer('Suphamit', 'ADB', 3).
lecturer('Nattapong', 'CC', 3).
lecturer('Nattapong', 'UXUI', 3).
lecturer('Pyrot', 'Graphic', 3).
lecturer('Big', 'SDP', 3).
lecturer('Suvijak', 'QA', 3).
lecturer('Yutthana', 'DL', 3).
lecturer('Nattapong', 'SVV', 4).
lecturer('Visit', 'OOP', 1).
